---

- name: grafana-install | add apt key
  become: true
  apt_key: url='{{grafana_apt_key}}' id=D59097AB

- name: grafana-install | add apt repo
  become: true
  apt_repository: repo='{{grafana_apt_repository}}'

- name: grafana-install | add apt beta repo
  become: true
  apt_repository: repo='{{grafana_apt_repository}}'

- set_fact: grafana_release='grafana={{grafana_version}}'

- name: grafana-install | Install Grafana
  become: true
  apt: name="{{grafana_release}}" update_cache=yes
  notify:
    - grafana restart
